
/* This file was generated by idltool 53.23. Do not edit */

#include "lz4_vectors.h"

STATIC uint32 VARARGS68K _main_UNIMPLEMENTED(struct LZ4IFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _main_Obtain,
    _main_Release,
    _main_UNIMPLEMENTED, /* Expunge */
    _main_UNIMPLEMENTED, /* Clone */
    _main_LZ4_versionNumber,
    _main_LZ4_compress,
    _main_LZ4_decompress_safe,
    _main_LZ4_compressBound,
    _main_LZ4_compress_limitedOutput,
    _main_LZ4_decompress_fast,
    _main_LZ4_decompress_safe_partial,
    _main_LZ4_compressHC,
    _main_LZ4_compressHC_limitedOutput,
    _main_LZ4_compressHC2,
    _main_LZ4_compressHC2_limitedOutput,
    _main_LZ4_sizeofStateHC,
    _main_LZ4_compressHC_withStateHC,
    _main_LZ4_compressHC_limitedOutput_withStateHC,
    _main_LZ4_compressHC2_withStateHC,
    _main_LZ4_compressHC2_limitedOutput_withStateHC,
    (APTR)-1
};
