#ifndef INLINE4_LZ4_H
#define INLINE4_LZ4_H

/*
** This file was auto generated by idltool 53.23.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_LZ4_H
#include <libraries/lz4.h>
#endif
#include <interfaces/lz4.h>

/* Inline macros for Interface "main" */
#define LZ4_versionNumber() ILZ4->LZ4_versionNumber()
#define LZ4_compress(source, dest, sourceSize) ILZ4->LZ4_compress((source), (dest), (sourceSize))
#define LZ4_decompress_safe(source, dest, compressedSize, maxDecompressedSize) ILZ4->LZ4_decompress_safe((source), (dest), (compressedSize), (maxDecompressedSize))
#define LZ4_compressBound(isize) ILZ4->LZ4_compressBound((isize))
#define LZ4_compress_limitedOutput(source, dest, sourceSize, maxOutputSize) ILZ4->LZ4_compress_limitedOutput((source), (dest), (sourceSize), (maxOutputSize))
#define LZ4_decompress_fast(source, dest, originalSize) ILZ4->LZ4_decompress_fast((source), (dest), (originalSize))
#define LZ4_decompress_safe_partial(source, dest, compressedSize, targetOutputSize, maxDecompressedSize) ILZ4->LZ4_decompress_safe_partial((source), (dest), (compressedSize), (targetOutputSize), (maxDecompressedSize))
#define LZ4_compressHC(source, dest, inputSize) ILZ4->LZ4_compressHC((source), (dest), (inputSize))
#define LZ4_compressHC_limitedOutput(source, dest, inputSize, maxOutputSize) ILZ4->LZ4_compressHC_limitedOutput((source), (dest), (inputSize), (maxOutputSize))
#define LZ4_compressHC2(source, dest, inputSize, compressionLevel) ILZ4->LZ4_compressHC2((source), (dest), (inputSize), (compressionLevel))
#define LZ4_compressHC2_limitedOutput(source, dest, inputSize, maxOutputSize, compressionLevel) ILZ4->LZ4_compressHC2_limitedOutput((source), (dest), (inputSize), (maxOutputSize), (compressionLevel))
#define LZ4_sizeofStateHC() ILZ4->LZ4_sizeofStateHC()
#define LZ4_compressHC_withStateHC(state, source, dest, inputSize) ILZ4->LZ4_compressHC_withStateHC((state), (source), (dest), (inputSize))
#define LZ4_compressHC_limitedOutput_withStateHC(state, source, dest, inputSize, maxOutputSize) ILZ4->LZ4_compressHC_limitedOutput_withStateHC((state), (source), (dest), (inputSize), (maxOutputSize))
#define LZ4_compressHC2_withStateHC(state, source, dest, inputSize, compressionLevel) ILZ4->LZ4_compressHC2_withStateHC((state), (source), (dest), (inputSize), (compressionLevel))
#define LZ4_compressHC2_limitedOutput_withStateHC(state, source, dest, inputSize, maxOutputSize, compressionLevel) ILZ4->LZ4_compressHC2_limitedOutput_withStateHC((state), (source), (dest), (inputSize), (maxOutputSize), (compressionLevel))

#endif /* INLINE4_LZ4_H */
